name: Create Repositories
run-name: Create Repositories
on: push

jobs:
  Create-repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run script to create Repositories
        run: python ./.github/scripts/create-repos.py
        env:
          ACCESS_TOKEN: ${{ secrets.personal_token }}