name: Create Repositories
run-name: Create Repositories
on: push

jobs:
  Treat-JSON:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JQ
        run: sudo apt-get install jq

      - name: Create repositories
        run: |
          JSON="./.github/example-files/repo-example.json"

          REPOSITORIES=($(jq -c '.repositories | .[] | .repo_name' $JSON))

          for repo_name in "${REPOSITORIES[@]}"; do
            REPO_INFO=$(jq -c ".repositories[] | select(.repo_name == \"$repo_name\")" "$JSON")
            echo " Creating Repository: $repo_name"
            curl -v -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.personal_token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/orgs/my-org-alex/repos \
              -d "{\"name\":\"$repo_name\",\"description\":\"This is your first repository\",\"private\":false,\"has_issues\":false,\"has_projects\":false,\"has_wiki\":false}"
            
            ENVIRONMENTS=$(echo "$REPO_INFO" | jq -c '.environments')
            echo "Creating Environments: $ENVIRONMENTS"
            for repo_env_info in $ENVIRONMENTS; do
              env_name=$(echo "$repo_env_info" | jq -r '.env_name')
              echo "Creating environment: $env_name"
              production=$(echo "$repo_env_info" | jq -r '.production')
              echo "Is prod: $production"

              curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.personal_token }}" \
              "https://api.github.com/repos/my-org-alex/$repository_name/environments" \
              -d "{\"name\":\"$env_name\",\"auto_merge\":false,\"production\":$production}"  
            done

            VARIABLES=$(echo "$REPO_INFO" | jq -c '.repo_variables')
            echo "Creating Variables: $VARIABLES"
            for repo_var_info in $VARIABLES; do
              repo_var_name=$(echo "$repo_var_info" | jq -r '.repo_var_name')
              value=$(echo "$repo_var_info" | jq -r '.value')

              curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.personal_token }}" \
              "https://api.github.com/repos/my-org-alex/$repository_name/actions/secrets/$repo_var_name" \
              -d "{\"value\":\"$value\"}"
            done

            SECRETS=$(echo "$REPO_INFO" | jq -c '.repo_secrets')
            echo "Creating Secrets: $SECRETS"
            for repo_secret_info in $SECRETS; do
              repo_secret_name=$(echo "$repo_secret_info" | jq -r '.repo_secret_name')
              value=$(echo "$repo_secret_info" | jq -r '.value')

              curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.personal_token }}" \
              "https://api.github.com/repos/my-org-alex/$repository_name/actions/secrets/$repo_secret_name" \
              -d "{\"encrypted_value\":\"$(echo -n $value | base64)\",\"key_id\":null}"
            done
          done