name: Create Repositories
on: push

jobs:
  Treat-JSON:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JQ
        run: sudo apt-get install jq

      - name: Treat json file
        run: |
          JSON="./.github/example-files/repo-example.json"

          REPOSITORIES=$(cat $JSON | jq -r '.repoNames[]')
      
      - name: Create Repositories
        run: |
          for repository_name in $REPOSITORIES; do
            echo "Creating repository: $repository_name"
            curl -v -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.personal_token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/orgs/my-org-alex/repos \
              -d "{\"name\":\"$repository_name\",\"description\":\"This is your first repository\",\"private\":false,\"has_issues\":false,\"has_projects\":false,\"has_wiki\":false}"
          done