name: Create Repositories
run-name: Create Repositories
on: push

jobs:
  Create-Repositories:
    runs-on: ubuntu-latest
    using: 'composite'
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Intall Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install --upgrade pip setuptools wheel
      
      - name: Run script to create Repositories
        run: python ./.github/scripts/creat-repos.py