name: Create Repositories
run-name: Create Repositories
on: push

jobs:
  Treat-JSON:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JQ
        run: sudo apt-get install jq

      - name: Create repositories
        run: |
          JSON="./.github/example-files/repo-example.json"

          # Extract repository names
          REPOSITORIES=($(jq -c '.repositories | .[] | .repo_name' "$JSON"))

          for repo in "${REPOSITORIES[@]}"; do
            echo "Repository: $repo"

            # Extract environments for the current repository as an array
            ENVIRONMENTS=$(jq -r --arg repo_name $repo '.repositories[] | select(.repo_name == $repo_name) | .environments[]' "$JSON")
            echo $ENVIRONMENTS

            for env_info in "${ENVIRONMENTS[@]}"; do
              env_name=$(echo "$env_info" | jq -r '.env_name')
              production=$(echo "$env_info" | jq -r '.production')

              echo "Environment: $env_name, Production: $production"
            done
          done