name: Create Repositories
run-name: Create Repositories
on: push

jobs:
  Create-repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pynacl
          
      - name: Run script to create Repositories
        run: python ./.github/scripts/create-repos.py
        env:
          ACCESS_TOKEN: ${{ secrets.personal_token }}
      
      - name: Get secrets
        run: |
            echo ${{ secrets.secret1 }} > ./.github/example-files/secret.txt
            echo ${{ secrets.secret2 }} > ./.github/example-files/secret.txt
            echo ${{ secrets.secret3 }} > ./.github/example-files/secret.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./.github/example-files/secret.txt